global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # FastAPI application metrics (when implemented)
  - job_name: 'qr-app'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    # Only scrape if metrics endpoint is available
    honor_labels: true

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 