# Static configuration (traefik.yml)
global:
  checkNewVersion: false  # Disable in production
  sendAnonymousUsage: false

log:
  level: INFO  # Change to INFO or WARNING in production
  format: json

# Access Logs Configuration
accessLog:
  filePath: "/logs/traefik/access.log"
  format: json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
    retryAttempts: true
    minDuration: "10ms"

# Metrics Configuration
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  web:
    address: ":80"
    # Add forwarded headers if behind another proxy
    forwardedHeaders:
      trustedIPs:
        # NEEDED: List of trusted proxy IPs
        - "127.0.0.1/32"
        - "10.0.0.0/8"
  
  websecure:
    address: ":443"
    # TLS configuration handled in dynamic_conf.yml
    http:
      tls: {}  # Empty TLS config, actual certificates in dynamic_conf.yml
  
  traefik:
    address: ":8080"  # Consider changing or restricting
    # NEEDED: Should this be exposed? If yes, how to secure?
  
  metrics:
    address: ":8082"
    # NEEDED: Should this be restricted to specific IPs?

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"  # Confirm if this stays the same
    exposedByDefault: false
    network: qr_generator_network            # Confirm network name
  file:
    directory: /etc/traefik/conf.d/
    watch: true

api:
  dashboard: true  # NEEDED: Should this be enabled in production?
  # NEEDED: How to secure the dashboard?
  insecure: false  # Changed from true for production

# Remove certificatesResolvers since we're using provided certificates 