http:
  routers:
    # --- Health Check (Public) - RESTORED to old working priority ---
    health-router:
      rule: "Host(`web.hccc.edu`, `webhost.hccc.edu`, `10.1.6.12`) && PathPrefix(`/health`)"
      service: api-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https@file
        - public-endpoints@file # Allow all IPs
        - security-headers@file
      priority: 900 # Higher priority than dashboard catch-all (800)

    health-secure-router:
      rule: "Host(`web.hccc.edu`, `webhost.hccc.edu`, `10.1.6.12`) && PathPrefix(`/health`)"
      service: api-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - public-endpoints@file
        - security-headers@file
      priority: 900 # Higher priority than dashboard catch-all (800)

    # --- Admin Endpoints (Internal Only) - RESTORED to old working priority ---
    admin-api-router:
      rule: "Host(`webhost.hccc.edu`, `10.1.6.12`) && PathPrefix(`/api/v1/admin/`)"
      service: api-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https@file
        - ip-whitelist@file      # Internal IPs only
        - dashboard-auth@file    # Basic Auth  
        - security-headers@file
      priority: 450 # RESTORED to match old working config

    admin-api-secure-router:
      rule: "Host(`webhost.hccc.edu`, `10.1.6.12`) && PathPrefix(`/api/v1/admin/`)"
      service: api-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - ip-whitelist@file      # Internal IPs only
        - dashboard-auth@file    # Basic Auth
        - security-headers@file
      priority: 450 # RESTORED to match old working config 