http:
  routers:
    # --- Health Check (Public) - Higher priority than dashboard ---
    health-router:
      rule: "PathPrefix(`/health`)" # Could be Host-specific if needed, but generally public
      service: api-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https@file
        - public-endpoints@file # Allow all IPs
        - security-headers@file
      priority: 800 # Higher than dashboard to catch health paths first

    health-secure-router:
      rule: "PathPrefix(`/health`)"
      service: api-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - public-endpoints@file
        - security-headers@file
      priority: 800 # Higher than dashboard

    # --- Admin Endpoints (Internal Only) ---
    admin-api-router:
      rule: "PathPrefix(`/api/v1/admin/`)"
      service: api-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https@file
        - ip-whitelist@file      # Internal IPs only
        - dashboard-auth@file    # Basic Auth  
        - security-headers@file
      priority: 750 # Higher than dashboard but lower than health

    admin-api-secure-router:
      rule: "PathPrefix(`/api/v1/admin/`)"
      service: api-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - ip-whitelist@file      # Internal IPs only
        - dashboard-auth@file    # Basic Auth
        - security-headers@file
      priority: 750 