http:
  routers:
    # --- Traefik Dashboard (Internal Only) ---
    dashboard-router: # Renamed for clarity
      rule: "Host(`traefik.10.1.6.12`)" # Or your preferred dashboard host
      service: api@internal # Special Traefik service
      entryPoints:
        - traefik # Make sure this entrypoint is defined in traefik.yml
      middlewares:
        - ip-whitelist@file
        - dashboard-auth@file # Added Basic Auth
      priority: 800 # Very high priority

    # --- Prometheus (Internal Only) ---
    prometheus-router:
      rule: "Host(`prometheus.10.1.6.12`) || (Host(`10.1.6.12`) && PathPrefix(`/prometheus`))"
      service: prometheus-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https@file
        - ip-whitelist@file
        - dashboard-auth@file
        - security-headers@file
      priority: 750

    prometheus-secure-router:
      rule: "Host(`prometheus.10.1.6.12`) || (Host(`10.1.6.12`) && PathPrefix(`/prometheus`))"
      service: prometheus-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - ip-whitelist@file
        - dashboard-auth@file
        - security-headers@file
      priority: 750

    # --- Grafana (Internal Only) ---
    grafana-router:
      rule: "Host(`grafana.10.1.6.12`) || (Host(`10.1.6.12`) && PathPrefix(`/grafana`))"
      service: grafana-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https@file
        - ip-whitelist@file
        - security-headers@file
      priority: 740

    grafana-secure-router:
      rule: "Host(`grafana.10.1.6.12`) || (Host(`10.1.6.12`) && PathPrefix(`/grafana`))"
      service: grafana-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - ip-whitelist@file
        - security-headers@file
      priority: 740

    # --- Localhost API Router (Higher priority than Grafana for localhost) ---
    localhost-api-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/`, `/health`, `/static/assets/`)"
      service: api-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https@file
        - public-endpoints@file  # Allow all IPs
        - security-headers@file
      priority: 730 # Higher than Grafana routes

    localhost-api-secure-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/`, `/health`, `/static/assets/`)"
      service: api-service
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - public-endpoints@file
        - security-headers@file
      priority: 730 